#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/opt/ohpc/pub/libs/gnu/openmpi/neuron/7.5.0"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/opt/ohpc/pub/libs/gnu/openmpi/neuron/7.5.0/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/vinicius/MESTRADO/modelo HH/x86_64/.libs/libnrnmech.so" "$@"
